    public function run(): void
    {
        $products = [
            // Electronics Category (category_id = 1) - 8 products
            [
                'name' => 'Smartphone X1 Pro',
                'description' => 'Latest smartphone with advanced features',
                'long_description' => 'The Smartphone X1 represents the pinnacle of mobile technology, featuring a stunning 6.7-inch OLED display, advanced camera system with AI-powered photography, and lightning-fast 5G connectivity. Built with premium materials and designed for the modern user.',
                'price' => 699.99,
                'stock_quantity' => 50,
                'sku' => 'PHONE-X1-001',
                'category_id' => 1,
                'brand' => 'TechCorp',
                'model' => 'X1 Pro',
                'weight' => 0.18,
                'dimensions' => '160.8 x 78.1 x 7.4 mm',
                'tags' => json_encode(['smartphone', '5G', 'premium', 'camera']),
                'meta_title' => 'Smartphone X1 - Premium 5G Mobile Phone | TechCorp',
                'meta_description' => 'Discover the Smartphone X1 with advanced features, 5G connectivity, and premium design. Perfect for professionals and tech enthusiasts.',
                'meta_keywords' => 'smartphone, 5G, mobile phone, TechCorp, premium',
                'slug' => 'smartphone-x1-pro',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800',
                    'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
                    'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800',
                ],
            ],
            [
                'name' => 'Laptop Pro 15',
                'description' => 'High-performance laptop for professionals',
                'long_description' => 'The Laptop Pro 15 is engineered for professionals who demand the best. Featuring the latest Intel processor, dedicated graphics, and a stunning 15.6-inch 4K display. Perfect for creative work, programming, and business applications.',
                'price' => 1299.99,
                'stock_quantity' => 25,
                'sku' => 'LAPTOP-PRO-15',
                'category_id' => 1,
                'brand' => 'ProTech',
                'model' => 'Pro 15 Elite',
                'weight' => 2.1,
                'dimensions' => '356 x 243 x 17.9 mm',
                'tags' => json_encode(['laptop', 'professional', '4K', 'Intel']),
                'meta_title' => 'Laptop Pro 15 - Professional 4K Laptop | ProTech',
                'meta_description' => 'High-performance Laptop Pro 15 with 4K display, Intel processor, and professional features for demanding users.',
                'meta_keywords' => 'laptop, professional, 4K, Intel, ProTech',
                'slug' => 'laptop-pro-15-elite',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800',
                    'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800',
                    'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800',
                ],
            ],
            [
                'name' => 'Wireless Bluetooth Headphones',
                'description' => 'Premium noise-cancelling wireless headphones',
                'long_description' => 'Experience crystal-clear audio with our premium wireless Bluetooth headphones. Featuring active noise cancellation, 30-hour battery life, and superior comfort for extended listening sessions. Perfect for music lovers and professionals.',
                'price' => 249.99,
                'stock_quantity' => 75,
                'sku' => 'HEAD-BT-001',
                'category_id' => 1,
                'brand' => 'AudioPro',
                'model' => 'BT-5000',
                'weight' => 0.28,
                'dimensions' => '200 x 180 x 85 mm',
                'tags' => json_encode(['headphones', 'wireless', 'bluetooth', 'noise-cancelling']),
                'meta_title' => 'Wireless Bluetooth Headphones - Premium Audio | AudioPro',
                'meta_description' => 'Premium wireless Bluetooth headphones with noise cancellation and 30-hour battery life.',
                'meta_keywords' => 'headphones, wireless, bluetooth, noise cancelling, audio',
                'slug' => 'wireless-bluetooth-headphones',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800',
                    'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800',
                    'https://images.unsplash.com/photo-1545127398-14699f92334b?w=800',
                ],
            ],
            [
                'name' => 'Smart Watch Series 8',
                'description' => 'Advanced smartwatch with health tracking',
                'long_description' => 'Stay connected and monitor your health with the Smart Watch Series 8. Features include heart rate monitoring, sleep tracking, GPS, water resistance, and a vibrant always-on display. Compatible with iOS and Android.',
                'price' => 399.99,
                'stock_quantity' => 60,
                'sku' => 'WATCH-S8-001',
                'category_id' => 1,
                'brand' => 'TechWatch',
                'model' => 'Series 8',
                'weight' => 0.05,
                'dimensions' => '44 x 44 x 10.7 mm',
                'tags' => json_encode(['smartwatch', 'fitness', 'health', 'wearable']),
                'meta_title' => 'Smart Watch Series 8 - Health Tracking | TechWatch',
                'meta_description' => 'Advanced smartwatch with health tracking, GPS, and long battery life.',
                'meta_keywords' => 'smartwatch, fitness tracker, health monitoring, wearable',
                'slug' => 'smart-watch-series-8',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800',
                    'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800',
                    'https://images.unsplash.com/photo-1579586337278-3befd40e17ee?w=800',
                ],
            ],
            [
                'name' => '4K Ultra HD Smart TV 55"',
                'description' => '55-inch 4K Smart TV with HDR',
                'long_description' => 'Transform your entertainment experience with this 55-inch 4K Ultra HD Smart TV. Features HDR10+ support, built-in streaming apps, voice control, and a sleek bezel-less design. Perfect for movies, gaming, and streaming content.',
                'price' => 799.99,
                'stock_quantity' => 30,
                'sku' => 'TV-4K-55-001',
                'category_id' => 1,
                'brand' => 'VisionTech',
                'model' => 'VT-55UHD',
                'weight' => 18.5,
                'dimensions' => '1230 x 710 x 85 mm',
                'tags' => json_encode(['tv', '4k', 'smart', 'hdr', 'entertainment']),
                'meta_title' => '4K Ultra HD Smart TV 55" - Premium Entertainment | VisionTech',
                'meta_description' => '55-inch 4K Smart TV with HDR10+, built-in streaming, and voice control.',
                'meta_keywords' => 'smart tv, 4k tv, hdr, streaming, entertainment',
                'slug' => '4k-ultra-hd-smart-tv-55',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800',
                    'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=800',
                    'https://images.unsplash.com/photo-1522869635100-9f4c5e86a037?w=800',
                ],
            ],
            [
                'name' => 'Gaming Console Pro',
                'description' => 'Next-generation gaming console',
                'long_description' => 'Experience next-generation gaming with the Gaming Console Pro. Features ray tracing, 4K gaming at 120fps, ultra-fast SSD storage, and backward compatibility. Includes wireless controller and access to thousands of games.',
                'price' => 499.99,
                'stock_quantity' => 40,
                'sku' => 'CONSOLE-PRO-001',
                'category_id' => 1,
                'brand' => 'GameTech',
                'model' => 'Pro Edition',
                'weight' => 4.5,
                'dimensions' => '390 x 260 x 104 mm',
                'tags' => json_encode(['gaming', 'console', '4k', 'entertainment']),
                'meta_title' => 'Gaming Console Pro - Next-Gen Gaming | GameTech',
                'meta_description' => 'Next-generation gaming console with 4K gaming, ray tracing, and ultra-fast SSD.',
                'meta_keywords' => 'gaming console, 4k gaming, ray tracing, entertainment',
                'slug' => 'gaming-console-pro',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800',
                    'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=800',
                    'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800',
                ],
            ],
            [
                'name' => 'Wireless Earbuds Pro',
                'description' => 'Premium true wireless earbuds',
                'long_description' => 'Enjoy premium sound quality with these true wireless earbuds. Features active noise cancellation, transparency mode, spatial audio, and up to 8 hours of battery life with charging case. Water and sweat resistant.',
                'price' => 179.99,
                'stock_quantity' => 90,
                'sku' => 'EARBUDS-PRO-001',
                'category_id' => 1,
                'brand' => 'SoundMax',
                'model' => 'Pro Air',
                'weight' => 0.05,
                'dimensions' => 'Case: 60 x 50 x 25 mm',
                'tags' => json_encode(['earbuds', 'wireless', 'audio', 'noise-cancelling']),
                'meta_title' => 'Wireless Earbuds Pro - Premium Audio | SoundMax',
                'meta_description' => 'Premium true wireless earbuds with noise cancellation and spatial audio.',
                'meta_keywords' => 'earbuds, wireless, noise cancelling, audio',
                'slug' => 'wireless-earbuds-pro',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=800',
                    'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800',
                    'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=800',
                ],
            ],
            [
                'name' => 'Tablet Pro 12.9"',
                'description' => 'Professional tablet with stunning display',
                'long_description' => 'The Tablet Pro 12.9" features a stunning Liquid Retina XDR display, powerful M2 chip, and support for Apple Pencil. Perfect for creative professionals, students, and anyone who needs a powerful portable device.',
                'price' => 1099.99,
                'stock_quantity' => 35,
                'sku' => 'TABLET-PRO-129',
                'category_id' => 1,
                'brand' => 'TabTech',
                'model' => 'Pro 12.9',
                'weight' => 0.68,
                'dimensions' => '280.6 x 214.9 x 6.4 mm',
                'tags' => json_encode(['tablet', 'professional', 'creative', 'portable']),
                'meta_title' => 'Tablet Pro 12.9" - Professional Tablet | TabTech',
                'meta_description' => 'Professional tablet with stunning display, powerful chip, and Apple Pencil support.',
                'meta_keywords' => 'tablet, professional, creative, portable, display',
                'slug' => 'tablet-pro-12-9',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800',
                    'https://images.unsplash.com/photo-1561154464-82e9adf32750?w=800',
                    'https://images.unsplash.com/photo-1526431543230-35bfb92e8e8e?w=800',
                ],
            ],

            // Clothing Category (category_id = 2) - 8 products
            [
                'name' => 'Organic Cotton T-Shirt',
                'description' => 'Comfortable cotton t-shirt in various colors',
                'long_description' => '100% organic cotton t-shirt that combines comfort with style. Available in multiple colors and sizes, this premium t-shirt is perfect for casual wear and everyday comfort. Made with sustainable materials and ethical manufacturing.',
                'price' => 19.99,
                'stock_quantity' => 100,
                'sku' => 'TSHIRT-COT-001',
                'category_id' => 2,
                'brand' => 'ComfortWear',
                'model' => 'Classic Fit',
                'weight' => 0.15,
                'dimensions' => 'Various sizes available',
                'tags' => json_encode(['cotton', 'organic', 'casual', 'comfortable']),
                'meta_title' => 'Organic Cotton T-Shirt - Comfortable Casual Wear | ComfortWear',
                'meta_description' => '100% organic cotton t-shirt in various colors. Comfortable, stylish, and perfect for everyday wear.',
                'meta_keywords' => 'cotton t-shirt, organic, casual wear, comfortable',
                'slug' => 'organic-cotton-t-shirt',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
                    'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800',
                    'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
                ],
            ],
            [
                'name' => 'Denim Jeans Classic',
                'description' => 'Classic fit denim jeans',
                'long_description' => 'Timeless classic fit denim jeans made from premium denim fabric. Features a comfortable waistband, durable construction, and a versatile design that works for casual and semi-formal occasions. Available in multiple washes and sizes.',
                'price' => 59.99,
                'stock_quantity' => 80,
                'sku' => 'JEANS-DEN-001',
                'category_id' => 2,
                'brand' => 'DenimCo',
                'model' => 'Classic Fit',
                'weight' => 0.5,
                'dimensions' => 'Various sizes available',
                'tags' => json_encode(['jeans', 'denim', 'casual', 'classic']),
                'meta_title' => 'Denim Jeans Classic - Premium Denim | DenimCo',
                'meta_description' => 'Classic fit denim jeans in multiple washes. Comfortable and durable.',
                'meta_keywords' => 'jeans, denim, casual, classic fit',
                'slug' => 'denim-jeans-classic',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800',
                    'https://images.unsplash.com/photo-1582418702059-97ebaf8e8e0e?w=800',
                    'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800',
                ],
            ],
            [
                'name' => 'Wool Winter Jacket',
                'description' => 'Warm and stylish winter jacket',
                'long_description' => 'Stay warm and stylish with this premium wool winter jacket. Features a water-resistant outer shell, insulated lining, multiple pockets, and a modern design. Perfect for cold weather and outdoor activities.',
                'price' => 149.99,
                'stock_quantity' => 45,
                'sku' => 'JACKET-WOOL-001',
                'category_id' => 2,
                'brand' => 'WinterWear',
                'model' => 'Classic',
                'weight' => 1.2,
                'dimensions' => 'Various sizes available',
                'tags' => json_encode(['jacket', 'winter', 'wool', 'warm']),
                'meta_title' => 'Wool Winter Jacket - Warm & Stylish | WinterWear',
                'meta_description' => 'Premium wool winter jacket with water-resistant shell and insulated lining.',
                'meta_keywords' => 'winter jacket, wool, warm, outdoor',
                'slug' => 'wool-winter-jacket',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800',
                    'https://images.unsplash.com/photo-1516826957135-700dedea698c?w=800',
                    'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800',
                ],
            ],
            [
                'name' => 'Running Sneakers',
                'description' => 'Comfortable running shoes',
                'long_description' => 'High-performance running sneakers designed for comfort and durability. Features breathable mesh upper, cushioned midsole, and durable rubber outsole. Perfect for running, jogging, and everyday athletic activities.',
                'price' => 89.99,
                'stock_quantity' => 70,
                'sku' => 'SNEAKERS-RUN-001',
                'category_id' => 2,
                'brand' => 'RunFast',
                'model' => 'Speed Pro',
                'weight' => 0.3,
                'dimensions' => 'Various sizes available',
                'tags' => json_encode(['sneakers', 'running', 'athletic', 'comfortable']),
                'meta_title' => 'Running Sneakers - High Performance | RunFast',
                'meta_description' => 'High-performance running sneakers with breathable mesh and cushioned midsole.',
                'meta_keywords' => 'running shoes, sneakers, athletic, comfortable',
                'slug' => 'running-sneakers',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
                    'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800',
                    'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800',
                ],
            ],
            [
                'name' => 'Silk Scarf Premium',
                'description' => 'Luxurious silk scarf',
                'long_description' => 'Add elegance to your outfit with this luxurious silk scarf. Made from 100% pure silk, featuring beautiful patterns and vibrant colors. Perfect for accessorizing and adding a touch of sophistication to any ensemble.',
                'price' => 39.99,
                'stock_quantity' => 120,
                'sku' => 'SCARF-SILK-001',
                'category_id' => 2,
                'brand' => 'LuxuryWear',
                'model' => 'Premium',
                'weight' => 0.05,
                'dimensions' => '90 x 90 cm',
                'tags' => json_encode(['scarf', 'silk', 'luxury', 'accessory']),
                'meta_title' => 'Silk Scarf Premium - Luxurious Accessory | LuxuryWear',
                'meta_description' => 'Luxurious 100% pure silk scarf with beautiful patterns and vibrant colors.',
                'meta_keywords' => 'silk scarf, luxury, accessory, elegant',
                'slug' => 'silk-scarf-premium',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800',
                    'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800',
                    'https://images.unsplash.com/photo-1590736969955-71cc94901144?w=800',
                ],
            ],
            [
                'name' => 'Leather Belt Classic',
                'description' => 'Genuine leather belt',
                'long_description' => 'Crafted from genuine leather, this classic belt features a timeless design and durable construction. Available in multiple colors and sizes. Perfect for both casual and formal wear.',
                'price' => 34.99,
                'stock_quantity' => 95,
                'sku' => 'BELT-LEATH-001',
                'category_id' => 2,
                'brand' => 'LeatherCraft',
                'model' => 'Classic',
                'weight' => 0.2,
                'dimensions' => 'Various sizes available',
                'tags' => json_encode(['belt', 'leather', 'accessory', 'classic']),
                'meta_title' => 'Leather Belt Classic - Genuine Leather | LeatherCraft',
                'meta_description' => 'Genuine leather belt with timeless design. Available in multiple colors and sizes.',
                'meta_keywords' => 'belt, leather, accessory, classic',
                'slug' => 'leather-belt-classic',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=800',
                    'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800',
                    'https://images.unsplash.com/photo-1624378515193-6bbdb73f2197?w=800',
                ],
            ],
            [
                'name' => 'Summer Dress Floral',
                'description' => 'Beautiful floral summer dress',
                'long_description' => 'Stay cool and stylish with this beautiful floral summer dress. Made from lightweight, breathable fabric with a flattering A-line silhouette. Perfect for warm weather, parties, and casual outings.',
                'price' => 49.99,
                'stock_quantity' => 65,
                'sku' => 'DRESS-FLOR-001',
                'category_id' => 2,
                'brand' => 'FashionStyle',
                'model' => 'Floral Print',
                'weight' => 0.25,
                'dimensions' => 'Various sizes available',
                'tags' => json_encode(['dress', 'summer', 'floral', 'casual']),
                'meta_title' => 'Summer Dress Floral - Beautiful & Stylish | FashionStyle',
                'meta_description' => 'Beautiful floral summer dress in lightweight, breathable fabric.',
                'meta_keywords' => 'dress, summer, floral, casual',
                'slug' => 'summer-dress-floral',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800',
                    'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800',
                    'https://images.unsplash.com/photo-1566479179817-278d6c0e0e1e?w=800',
                ],
            ],
            [
                'name' => 'Hooded Sweatshirt',
                'description' => 'Comfortable hooded sweatshirt',
                'long_description' => 'Stay cozy with this comfortable hooded sweatshirt. Made from soft, warm fabric with a relaxed fit. Features a front pocket and adjustable drawstring hood. Perfect for casual wear and lounging.',
                'price' => 44.99,
                'stock_quantity' => 85,
                'sku' => 'SWEAT-HOOD-001',
                'category_id' => 2,
                'brand' => 'ComfortWear',
                'model' => 'Classic Hoodie',
                'weight' => 0.6,
                'dimensions' => 'Various sizes available',
                'tags' => json_encode(['sweatshirt', 'hoodie', 'casual', 'comfortable']),
                'meta_title' => 'Hooded Sweatshirt - Comfortable & Cozy | ComfortWear',
                'meta_description' => 'Comfortable hooded sweatshirt in soft, warm fabric. Perfect for casual wear.',
                'meta_keywords' => 'sweatshirt, hoodie, casual, comfortable',
                'slug' => 'hooded-sweatshirt',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1556821840-3a63f95609a4?w=800',
                    'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?w=800',
                    'https://images.unsplash.com/photo-1556821843-0c1c0fe92f8a?w=800',
                ],
            ],

            // Home & Garden Category (category_id = 3) - 7 products
            [
                'name' => 'Modern Sofa Set',
                'description' => 'Comfortable 3-seater sofa set',
                'long_description' => 'Transform your living room with this modern 3-seater sofa set. Features premium upholstery, comfortable cushions, and a sleek contemporary design. Perfect for family gatherings and relaxation.',
                'price' => 899.99,
                'stock_quantity' => 15,
                'sku' => 'SOFA-MOD-001',
                'category_id' => 3,
                'brand' => 'HomeComfort',
                'model' => 'Modern 3-Seater',
                'weight' => 85.0,
                'dimensions' => '220 x 90 x 85 cm',
                'tags' => json_encode(['sofa', 'furniture', 'living room', 'modern']),
                'meta_title' => 'Modern Sofa Set - Comfortable Living Room Furniture | HomeComfort',
                'meta_description' => 'Modern 3-seater sofa set with premium upholstery and comfortable cushions.',
                'meta_keywords' => 'sofa, furniture, living room, modern',
                'slug' => 'modern-sofa-set',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                    'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                    'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=800',
                ],
            ],
            [
                'name' => 'Garden Tool Set',
                'description' => 'Complete garden tool set',
                'long_description' => 'Everything you need for gardening in one set. Includes trowel, pruner, weeder, cultivator, and more. Made from durable stainless steel with comfortable ergonomic handles. Perfect for both beginners and experienced gardeners.',
                'price' => 49.99,
                'stock_quantity' => 50,
                'sku' => 'GARDEN-TOOL-001',
                'category_id' => 3,
                'brand' => 'GardenPro',
                'model' => 'Complete Set',
                'weight' => 2.5,
                'dimensions' => 'Tool bag: 45 x 30 x 25 cm',
                'tags' => json_encode(['garden', 'tools', 'gardening', 'outdoor']),
                'meta_title' => 'Garden Tool Set - Complete Gardening Tools | GardenPro',
                'meta_description' => 'Complete garden tool set with durable stainless steel tools and ergonomic handles.',
                'meta_keywords' => 'garden tools, gardening, outdoor, tools',
                'slug' => 'garden-tool-set',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
                    'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800',
                    'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
                ],
            ],
            [
                'name' => 'Ceramic Dinner Set',
                'description' => 'Elegant 16-piece dinner set',
                'long_description' => 'Serve meals in style with this elegant 16-piece ceramic dinner set. Includes 4 dinner plates, 4 salad plates, 4 bowls, and 4 mugs. Features a beautiful modern design and dishwasher-safe finish.',
                'price' => 79.99,
                'stock_quantity' => 40,
                'sku' => 'DINNER-SET-001',
                'category_id' => 3,
                'brand' => 'TableWare',
                'model' => 'Elegant 16-Piece',
                'weight' => 5.2,
                'dimensions' => 'Various sizes',
                'tags' => json_encode(['dinnerware', 'ceramic', 'tableware', 'kitchen']),
                'meta_title' => 'Ceramic Dinner Set - Elegant Tableware | TableWare',
                'meta_description' => 'Elegant 16-piece ceramic dinner set with modern design. Dishwasher-safe.',
                'meta_keywords' => 'dinnerware, ceramic, tableware, kitchen',
                'slug' => 'ceramic-dinner-set',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800',
                    'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800',
                    'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800',
                ],
            ],
            [
                'name' => 'LED Floor Lamp',
                'description' => 'Modern LED floor lamp',
                'long_description' => 'Illuminate your space with this modern LED floor lamp. Features adjustable brightness levels, energy-efficient LED bulbs, and a sleek contemporary design. Perfect for reading, working, or creating ambiance.',
                'price' => 89.99,
                'stock_quantity' => 35,
                'sku' => 'LAMP-LED-001',
                'category_id' => 3,
                'brand' => 'LightHome',
                'model' => 'Modern LED',
                'weight' => 3.5,
                'dimensions' => '160 x 30 x 30 cm',
                'tags' => json_encode(['lamp', 'led', 'lighting', 'modern']),
                'meta_title' => 'LED Floor Lamp - Modern Lighting | LightHome',
                'meta_description' => 'Modern LED floor lamp with adjustable brightness and energy-efficient design.',
                'meta_keywords' => 'lamp, led, lighting, modern',
                'slug' => 'led-floor-lamp',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800',
                    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
                    'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800',
                ],
            ],
            [
                'name' => 'Indoor Plant Collection',
                'description' => 'Set of 3 indoor plants',
                'long_description' => 'Bring nature indoors with this collection of 3 beautiful indoor plants. Includes easy-care varieties perfect for beginners. Comes with decorative pots and care instructions. Perfect for home or office decoration.',
                'price' => 39.99,
                'stock_quantity' => 60,
                'sku' => 'PLANT-INDOOR-001',
                'category_id' => 3,
                'brand' => 'GreenLife',
                'model' => 'Starter Collection',
                'weight' => 4.0,
                'dimensions' => 'Various pot sizes',
                'tags' => json_encode(['plants', 'indoor', 'decoration', 'garden']),
                'meta_title' => 'Indoor Plant Collection - Home Decoration | GreenLife',
                'meta_description' => 'Set of 3 beautiful indoor plants with decorative pots. Perfect for home decoration.',
                'meta_keywords' => 'plants, indoor, decoration, garden',
                'slug' => 'indoor-plant-collection',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
                    'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=800',
                    'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800',
                ],
            ],
            [
                'name' => 'Coffee Table Modern',
                'description' => 'Sleek modern coffee table',
                'long_description' => 'Add style to your living room with this sleek modern coffee table. Features a tempered glass top, metal frame, and spacious storage shelf. Perfect for holding drinks, books, and decorative items.',
                'price' => 199.99,
                'stock_quantity' => 25,
                'sku' => 'TABLE-COFFEE-001',
                'category_id' => 3,
                'brand' => 'FurnitureStyle',
                'model' => 'Modern Glass',
                'weight' => 18.0,
                'dimensions' => '120 x 60 x 45 cm',
                'tags' => json_encode(['table', 'coffee table', 'furniture', 'modern']),
                'meta_title' => 'Coffee Table Modern - Sleek Design | FurnitureStyle',
                'meta_description' => 'Sleek modern coffee table with tempered glass top and metal frame.',
                'meta_keywords' => 'coffee table, furniture, modern, living room',
                'slug' => 'coffee-table-modern',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=800',
                    'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                    'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=800',
                ],
            ],
            [
                'name' => 'Bedding Set Premium',
                'description' => 'Luxurious 4-piece bedding set',
                'long_description' => 'Sleep in comfort with this luxurious 4-piece bedding set. Made from 100% Egyptian cotton with a high thread count. Includes duvet cover, fitted sheet, flat sheet, and 2 pillowcases. Available in multiple colors.',
                'price' => 129.99,
                'stock_quantity' => 55,
                'sku' => 'BEDDING-PREM-001',
                'category_id' => 3,
                'brand' => 'SleepLux',
                'model' => 'Premium 4-Piece',
                'weight' => 1.8,
                'dimensions' => 'Queen size',
                'tags' => json_encode(['bedding', 'sheets', 'bedroom', 'luxury']),
                'meta_title' => 'Bedding Set Premium - Luxurious Bedding | SleepLux',
                'meta_description' => 'Luxurious 4-piece bedding set made from 100% Egyptian cotton.',
                'meta_keywords' => 'bedding, sheets, bedroom, luxury',
                'slug' => 'bedding-set-premium',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=800',
                    'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=800',
                    'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
                ],
            ],

            // Sports & Outdoors Category (category_id = 4) - 7 products
            [
                'name' => 'Yoga Mat Premium',
                'description' => 'Non-slip premium yoga mat',
                'long_description' => 'Practice yoga with confidence on this premium non-slip yoga mat. Features extra-thick cushioning, eco-friendly materials, and a carrying strap. Perfect for yoga, pilates, and fitness exercises.',
                'price' => 34.99,
                'stock_quantity' => 75,
                'sku' => 'YOGA-MAT-001',
                'category_id' => 4,
                'brand' => 'FitLife',
                'model' => 'Premium Pro',
                'weight' => 1.2,
                'dimensions' => '183 x 61 x 0.6 cm',
                'tags' => json_encode(['yoga', 'mat', 'fitness', 'exercise']),
                'meta_title' => 'Yoga Mat Premium - Non-Slip Yoga Mat | FitLife',
                'meta_description' => 'Premium non-slip yoga mat with extra-thick cushioning and eco-friendly materials.',
                'meta_keywords' => 'yoga mat, fitness, exercise, yoga',
                'slug' => 'yoga-mat-premium',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800',
                    'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
                    'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800',
                ],
            ],
            [
                'name' => 'Camping Tent 4-Person',
                'description' => 'Spacious 4-person camping tent',
                'long_description' => 'Enjoy outdoor adventures with this spacious 4-person camping tent. Features waterproof material, easy setup, ventilation windows, and a rainfly. Perfect for family camping trips and outdoor excursions.',
                'price' => 149.99,
                'stock_quantity' => 30,
                'sku' => 'TENT-CAMP-001',
                'category_id' => 4,
                'brand' => 'OutdoorPro',
                'model' => '4-Person',
                'weight' => 5.5,
                'dimensions' => '280 x 240 x 150 cm',
                'tags' => json_encode(['tent', 'camping', 'outdoor', 'adventure']),
                'meta_title' => 'Camping Tent 4-Person - Spacious & Waterproof | OutdoorPro',
                'meta_description' => 'Spacious 4-person camping tent with waterproof material and easy setup.',
                'meta_keywords' => 'tent, camping, outdoor, adventure',
                'slug' => 'camping-tent-4-person',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800',
                    'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800',
                    'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800',
                ],
            ],
            [
                'name' => 'Dumbbell Set Adjustable',
                'description' => 'Adjustable dumbbell set',
                'long_description' => 'Build strength at home with this adjustable dumbbell set. Features quick-change weight system, comfortable grips, and durable construction. Adjustable from 5 to 25 pounds per dumbbell. Perfect for home workouts.',
                'price' => 199.99,
                'stock_quantity' => 40,
                'sku' => 'DUMBBELL-ADJ-001',
                'category_id' => 4,
                'brand' => 'FitGear',
                'model' => 'Adjustable Pro',
                'weight' => 22.7,
                'dimensions' => '35 x 15 x 15 cm per dumbbell',
                'tags' => json_encode(['dumbbell', 'weights', 'fitness', 'exercise']),
                'meta_title' => 'Dumbbell Set Adjustable - Home Workout | FitGear',
                'meta_description' => 'Adjustable dumbbell set with quick-change weight system. Perfect for home workouts.',
                'meta_keywords' => 'dumbbell, weights, fitness, exercise',
                'slug' => 'dumbbell-set-adjustable',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
                    'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800',
                    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
                ],
            ],
            [
                'name' => 'Bicycle Mountain Bike',
                'description' => 'Durable mountain bike',
                'long_description' => 'Conquer any terrain with this durable mountain bike. Features front suspension, 21-speed gear system, disc brakes, and all-terrain tires. Perfect for mountain trails, city commuting, and outdoor adventures.',
                'price' => 449.99,
                'stock_quantity' => 20,
                'sku' => 'BIKE-MTB-001',
                'category_id' => 4,
                'brand' => 'BikePro',
                'model' => 'Mountain Trail',
                'weight' => 14.5,
                'dimensions' => 'Frame: 18 inches',
                'tags' => json_encode(['bicycle', 'mountain bike', 'outdoor', 'cycling']),
                'meta_title' => 'Bicycle Mountain Bike - Durable & Reliable | BikePro',
                'meta_description' => 'Durable mountain bike with front suspension and 21-speed gear system.',
                'meta_keywords' => 'bicycle, mountain bike, outdoor, cycling',
                'slug' => 'bicycle-mountain-bike',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
                    'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800',
                    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
                ],
            ],
            [
                'name' => 'Tennis Racket Pro',
                'description' => 'Professional tennis racket',
                'long_description' => 'Improve your game with this professional tennis racket. Features lightweight carbon fiber construction, comfortable grip, and optimal string tension. Perfect for intermediate to advanced players.',
                'price' => 89.99,
                'stock_quantity' => 45,
                'sku' => 'RACKET-TEN-001',
                'category_id' => 4,
                'brand' => 'SportPro',
                'model' => 'Pro Series',
                'weight' => 0.3,
                'dimensions' => '68.5 cm length',
                'tags' => json_encode(['tennis', 'racket', 'sports', 'professional']),
                'meta_title' => 'Tennis Racket Pro - Professional Quality | SportPro',
                'meta_description' => 'Professional tennis racket with lightweight carbon fiber construction.',
                'meta_keywords' => 'tennis racket, sports, professional, tennis',
                'slug' => 'tennis-racket-pro',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1622163642998-8c0fcb74b071?w=800',
                    'https://images.unsplash.com/photo-1622279457486-62dcc4a431f7?w=800',
                    'https://images.unsplash.com/photo-1622163642998-8c0fcb74b071?w=800',
                ],
            ],
            [
                'name' => 'Swimming Goggles',
                'description' => 'Anti-fog swimming goggles',
                'long_description' => 'Swim with clear vision using these anti-fog swimming goggles. Features UV protection, comfortable silicone seal, adjustable strap, and leak-proof design. Perfect for pool swimming and training.',
                'price' => 24.99,
                'stock_quantity' => 100,
                'sku' => 'GOGGLES-SWIM-001',
                'category_id' => 4,
                'brand' => 'AquaPro',
                'model' => 'Anti-Fog',
                'weight' => 0.05,
                'dimensions' => 'One size fits all',
                'tags' => json_encode(['goggles', 'swimming', 'sports', 'aquatic']),
                'meta_title' => 'Swimming Goggles - Anti-Fog Design | AquaPro',
                'meta_description' => 'Anti-fog swimming goggles with UV protection and comfortable silicone seal.',
                'meta_keywords' => 'goggles, swimming, sports, aquatic',
                'slug' => 'swimming-goggles',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1551524164-6cf77f5e1d66?w=800',
                    'https://images.unsplash.com/photo-1551524164-6cf77f5e1d66?w=800',
                    'https://images.unsplash.com/photo-1551524164-6cf77f5e1d66?w=800',
                ],
            ],
            [
                'name' => 'Hiking Backpack 40L',
                'description' => 'Durable hiking backpack',
                'long_description' => 'Carry your gear comfortably with this durable 40L hiking backpack. Features multiple compartments, hydration system compatibility, adjustable straps, and weather-resistant material. Perfect for day hikes and outdoor adventures.',
                'price' => 79.99,
                'stock_quantity' => 50,
                'sku' => 'BACKPACK-HIK-001',
                'category_id' => 4,
                'brand' => 'AdventureGear',
                'model' => '40L Pro',
                'weight' => 1.2,
                'dimensions' => '55 x 30 x 25 cm',
                'tags' => json_encode(['backpack', 'hiking', 'outdoor', 'adventure']),
                'meta_title' => 'Hiking Backpack 40L - Durable & Spacious | AdventureGear',
                'meta_description' => 'Durable 40L hiking backpack with multiple compartments and weather-resistant material.',
                'meta_keywords' => 'backpack, hiking, outdoor, adventure',
                'slug' => 'hiking-backpack-40l',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',
                    'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800',
                    'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',
                ],
            ],

            // Books & Media Category (category_id = 5) - 6 products
            [
                'name' => 'The Great Novel - Hardcover',
                'description' => 'Bestselling fiction novel',
                'long_description' => 'Immerse yourself in this bestselling fiction novel that has captivated readers worldwide. A compelling story of adventure, love, and discovery. Hardcover edition with beautiful cover design.',
                'price' => 24.99,
                'stock_quantity' => 80,
                'sku' => 'BOOK-NOVEL-001',
                'category_id' => 5,
                'brand' => 'BookHouse',
                'model' => 'Hardcover Edition',
                'weight' => 0.6,
                'dimensions' => '23 x 15 x 3 cm',
                'tags' => json_encode(['book', 'novel', 'fiction', 'literature']),
                'meta_title' => 'The Great Novel - Bestselling Fiction | BookHouse',
                'meta_description' => 'Bestselling fiction novel in beautiful hardcover edition.',
                'meta_keywords' => 'book, novel, fiction, literature',
                'slug' => 'the-great-novel-hardcover',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800',
                    'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=800',
                    'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=800',
                ],
            ],
            [
                'name' => 'Cookbook: Modern Recipes',
                'description' => 'Comprehensive modern cookbook',
                'long_description' => 'Discover delicious recipes with this comprehensive modern cookbook. Features over 200 recipes with step-by-step instructions, beautiful photography, and tips from professional chefs. Perfect for home cooks of all levels.',
                'price' => 29.99,
                'stock_quantity' => 65,
                'sku' => 'BOOK-COOK-001',
                'category_id' => 5,
                'brand' => 'CulinaryPress',
                'model' => 'Modern Edition',
                'weight' => 1.2,
                'dimensions' => '26 x 20 x 2 cm',
                'tags' => json_encode(['cookbook', 'recipes', 'food', 'cooking']),
                'meta_title' => 'Cookbook: Modern Recipes - Delicious Recipes | CulinaryPress',
                'meta_description' => 'Comprehensive modern cookbook with over 200 recipes and professional chef tips.',
                'meta_keywords' => 'cookbook, recipes, food, cooking',
                'slug' => 'cookbook-modern-recipes',
                'created_by' => 1,
                'updated_by' => 1,
                'images' => [
                    'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800',
                    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
                    'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800',   
                ],
            ]
    ];
}
